[project]
name="jssecpro"
version="1.1.0"
description="Advanced JavaScript Security Analysis Framework (plugin-based)"
requires-python=">=3.12.9"
dependencies=["requests","beautifulsoup4","rich","pyyaml","jinja2"]
[project.scripts]
jssecpro="jssecpro.cli:main"
